--------- Table ---------
CREATE TABLE IF NOT EXISTS department_and_faculty (
    department TEXT PRIMARY KEY,
    dept_code TEXT,
    school TEXT,
    school_code TEXT,
    faculty TEXT,
    faculty_code TEXT
);

--------- Insert Values ---------
INSERT INTO department_and_faculty (department, dept_code, school, school_code, faculty, faculty_code) VALUES
('Faculty of Arts - Admin', 'CCH_H1_5_01', 'Faculty of Arts, Admin, Centres and Institute', 'CCH_H1_4_01', 'Faculty of Arts', 'CCH_H1_3_01'),
('Faculty of Arts - Centres and Institutes', 'CCH_H1_5_02', 'Faculty of Arts, Admin, Centres and Institute', 'CCH_H1_4_01', 'Faculty of Arts', 'CCH_H1_3_01'),
('Asia Institute (D)', 'CCH_H1_5_03', 'Asia Institute', 'CCH_H1_4_02', 'Faculty of Arts', 'CCH_H1_3_01'),
('Graduate School of Humanities and Social Sciences (D)', 'CCH_H1_5_04', 'Graduate School of Humanities and Social Sciences', 'CCH_H1_4_03', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Culture and Communication (D)', 'CCH_H1_5_05', 'School of Culture and Communication', 'CCH_H1_4_04', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Historical and Philosophical Studies (D)', 'CCH_H1_5_06', 'School of Historical and Philosophical Studies', 'CCH_H1_4_05', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Languages and Linguistics (D)', 'CCH_H1_5_07', 'School of Languages and Linguistics', 'CCH_H1_4_06', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Social and Political Sciences (D)', 'CCH_H1_5_08', 'School of Social and Political Sciences', 'CCH_H1_4_07', 'Faculty of Arts', 'CCH_H1_3_01'),
('Asia Institute - Centres and Institutes', 'CCH_H1_5_199', 'Asia Institute', 'CCH_H1_4_02', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Languages and Linguistics - Centres and Institutes', 'CCH_H1_5_200', 'School of Languages and Linguistics', 'CCH_H1_4_06', 'Faculty of Arts', 'CCH_H1_3_01'),
('School of Social and Political Sciences - Centres and Institutes', 'CCH_H1_5_201', 'School of Social and Political Sciences', 'CCH_H1_4_07', 'Faculty of Arts', 'CCH_H1_3_01'),
('The Peter Doherty Institute for Infection and Immunity', 'CCH_H1_5_09', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Academy of Surgical Anatomy (MDHS)', 'CCH_H1_5_204', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Teaching Health Clinics', 'CCH_H1_5_205', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Clinical Research Support (MISCH)', 'CCH_H1_5_206', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Academic Centre for Health (MACH)', 'CCH_H1_5_207', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Faculty of Medicine, Dentistry and Health Sciences - Admin (D)', 'CCH_H1_5_48', 'Faculty of Medicine, Dentistry and Health Sciences - Admin', 'CCH_H1_4_23', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Centre for Cancer Research', 'CCH_H1_5_49', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Centre for Collaborative Practice', 'CCH_H1_5_50', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Centre for Digital Transformation of Health', 'CCH_H1_5_51', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Centre for Youth Mental Health (Orygen)', 'CCH_H1_5_52', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Comprehensive Dementia Centre', 'CCH_H1_5_53', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Medical Biology (WEHI)', 'CCH_H1_5_54', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Florey Department of Neuroscience and Mental Health', 'CCH_H1_5_55', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Medical Bionics Department', 'CCH_H1_5_56', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Bioinformatics (VLSCI)', 'CCH_H1_5_57', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Poche Centre for Indigenous Health', 'CCH_H1_5_60', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('National Ageing Research Institute', 'CCH_H1_5_61', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Australian Biocommons', 'CCH_H1_5_62', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('The Sir Peter MacCallum Department of Oncology', 'CCH_H1_5_63', 'MDHS Centres and Institutes', 'CCH_H1_4_08', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Dental School (D)', 'CCH_H1_5_65', 'Melbourne Dental School', 'CCH_H1_4_24', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne Medical School - Admin', 'CCH_H1_5_66', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Baker Department of Cardiometabolic Health', 'CCH_H1_5_69', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Clinical Pathology', 'CCH_H1_5_70', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Critical Care', 'CCH_H1_5_71', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of General Practice and Primary Care', 'CCH_H1_5_72', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Infectious Diseases', 'CCH_H1_5_73', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Medical Education', 'CCH_H1_5_74', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Medicine', 'CCH_H1_5_75', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Obstetrics, Gynaecology and Newborn Health', 'CCH_H1_5_76', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Paediatrics', 'CCH_H1_5_77', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Psychiatry', 'CCH_H1_5_78', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Radiology', 'CCH_H1_5_79', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Rural Health', 'CCH_H1_5_80', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Surgery', 'CCH_H1_5_81', 'Melbourne Medical School', 'CCH_H1_4_25', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne School of Health Sciences - Admin', 'CCH_H1_5_82', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Audiology and Speech Pathology', 'CCH_H1_5_83', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Nursing', 'CCH_H1_5_84', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Optometry and Vision Sciences', 'CCH_H1_5_85', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Physiotherapy', 'CCH_H1_5_86', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Social Work', 'CCH_H1_5_87', 'Melbourne School of Health Sciences', 'CCH_H1_4_26', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne School of Population and Global Health (D)', 'CCH_H1_5_88', 'Melbourne School of Population and Global Health', 'CCH_H1_4_27', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne School of Population and Global Health - Centres and Institutes', 'CCH_H1_5_89', 'Melbourne School of Population and Global Health', 'CCH_H1_4_27', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne School of Psychological Sciences (D)', 'CCH_H1_5_90', 'Melbourne School of Psychological Sciences', 'CCH_H1_4_28', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Melbourne School of Psychological Sciences - Centres and Institutes', 'CCH_H1_5_91', 'Melbourne School of Psychological Sciences', 'CCH_H1_4_28', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('School of Biomedical Sciences - Admin', 'CCH_H1_5_92', 'School of Biomedical Sciences', 'CCH_H1_4_29', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Anatomy and Physiology', 'CCH_H1_5_93', 'School of Biomedical Sciences', 'CCH_H1_4_29', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Biochemistry and Pharmacology', 'CCH_H1_5_94', 'School of Biomedical Sciences', 'CCH_H1_4_29', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Department of Microbiology and Immunology', 'CCH_H1_5_95', 'School of Biomedical Sciences', 'CCH_H1_4_29', 'Faculty of Medicine, Dentistry and Health Sciences', 'CCH_H1_3_02'),
('Business Services Directorate', 'CCH_H1_5_10', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Client Services', 'CCH_H1_5_11', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Academic Technology', 'CCH_H1_5_12', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Office of the Chief Operating Officer (D)', 'CCH_H1_5_121', 'Office of the Chief Operating Officer ', 'CCH_H1_4_43', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Governance', 'CCH_H1_5_122', 'Office of the Chief Operating Officer ', 'CCH_H1_4_43', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Strategy, Planning and Performance', 'CCH_H1_5_123', 'Office of the Chief Operating Officer ', 'CCH_H1_4_43', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Office of the CFO', 'CCH_H1_5_124', 'Chief Financial Officer Group', 'CCH_H1_4_44', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Corporate Finance, Property and Sustainability', 'CCH_H1_5_125', 'Chief Financial Officer Group', 'CCH_H1_4_44', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Financial Planning, Partnering and Advisory', 'CCH_H1_5_126', 'Chief Financial Officer Group', 'CCH_H1_4_44', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Procurement', 'CCH_H1_5_127', 'Chief Financial Officer Group', 'CCH_H1_4_44', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Strategic Financial Initiatives', 'CCH_H1_5_128', 'Chief Financial Officer Group', 'CCH_H1_4_44', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Office of General Counsel', 'CCH_H1_5_129', 'Legal and Risk', 'CCH_H1_4_45', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Health & Safety', 'CCH_H1_5_13', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Information Governance Services', 'CCH_H1_5_130', 'Legal and Risk', 'CCH_H1_4_45', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Legal Services', 'CCH_H1_5_131', 'Legal and Risk', 'CCH_H1_4_45', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Risk and Assurance', 'CCH_H1_5_132', 'Legal and Risk', 'CCH_H1_4_45', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Operational Performance Directorate', 'CCH_H1_5_133', 'Operational Performance', 'CCH_H1_4_46', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Change Practice (OPG)', 'CCH_H1_5_135', 'Operational Performance', 'CCH_H1_4_46', 'Chief Operating Officer', 'CCH_H1_3_03'),
('University Decision Support', 'CCH_H1_5_136', 'Operational Performance', 'CCH_H1_4_46', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Projects and Portfolio Management', 'CCH_H1_5_138', 'Operational Performance', 'CCH_H1_4_46', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Finance Services', 'CCH_H1_5_14', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Service Experience & Design', 'CCH_H1_5_140', 'Operational Performance', 'CCH_H1_4_46', 'Chief Operating Officer', 'CCH_H1_3_03'),
('RIC Directorate', 'CCH_H1_5_141', 'Research, Innovation and Commercialisation', 'CCH_H1_4_47', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Commercialisation Ventures', 'CCH_H1_5_142', 'Research, Innovation and Commercialisation', 'CCH_H1_4_47', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Innovation & Enterprise', 'CCH_H1_5_143', 'Research, Innovation and Commercialisation', 'CCH_H1_4_47', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Melbourne Entrepreneurial Centre (MEC)', 'CCH_H1_5_144', 'Research, Innovation and Commercialisation', 'CCH_H1_4_47', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Office of Research Management', 'CCH_H1_5_145', 'Research, Innovation and Commercialisation', 'CCH_H1_4_47', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Student and Scholarly Services Directorate', 'CCH_H1_5_146', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Future Students', 'CCH_H1_5_147', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Murrup Barak', 'CCH_H1_5_148', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Enterprise Technology', 'CCH_H1_5_15', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('University Colleges and Residential Life', 'CCH_H1_5_150', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Scholarly Services', 'CCH_H1_5_151', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Student Administration', 'CCH_H1_5_152', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Student Success', 'CCH_H1_5_154', 'Student and Scholarly Services', 'CCH_H1_4_48', 'Chief Operating Officer', 'CCH_H1_3_03'),
('HR Services', 'CCH_H1_5_16', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Research Computing Services', 'CCH_H1_5_17', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Campus Management', 'CCH_H1_5_18', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Planning & Assurance', 'CCH_H1_5_19', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Cybersecurity', 'CCH_H1_5_20', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Melbourne Bio-Resources', 'CCH_H1_5_21', 'Business Services', 'CCH_H1_4_09', 'Chief Operating Officer', 'CCH_H1_3_03'),
('Faculty of Architecture, Building and Planning - Admin', 'CCH_H1_5_22', 'Faculty of Architecture, Building and Planning, Admin, Centres and Institute', 'CCH_H1_4_10', 'Faculty of Architecture, Building and Planning', 'CCH_H1_3_04'),
('Faculty of Architecture, Building and Planning - Centres and Institutes', 'CCH_H1_5_23', 'Faculty of Architecture, Building and Planning, Admin, Centres and Institute', 'CCH_H1_4_10', 'Faculty of Architecture, Building and Planning', 'CCH_H1_3_04'),
('Faculty of Architecture, Building and Planning (D)', 'CCH_H1_5_24', 'Faculty of Architecture, Building and Planning (S)', 'CCH_H1_4_11', 'Faculty of Architecture, Building and Planning', 'CCH_H1_3_04'),
('Faculty of Business and Economics - Admin', 'CCH_H1_5_26', 'Faculty of Business and Economics, Admin, Centres and Institute', 'CCH_H1_4_13', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Faculty of Business and Economics - Centres and Institutes', 'CCH_H1_5_27', 'Faculty of Business and Economics, Admin, Centres and Institute', 'CCH_H1_4_13', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Department of Accounting', 'CCH_H1_5_28', 'Faculty of Business and Economics (S)', 'CCH_H1_4_14', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Department of Business Administration', 'CCH_H1_5_29', 'Faculty of Business and Economics (S)', 'CCH_H1_4_14', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Department of Economics', 'CCH_H1_5_30', 'Faculty of Business and Economics (S)', 'CCH_H1_4_14', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Department of Finance', 'CCH_H1_5_31', 'Faculty of Business and Economics (S)', 'CCH_H1_4_14', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('Department of Management and Marketing', 'CCH_H1_5_32', 'Faculty of Business and Economics (S)', 'CCH_H1_4_14', 'Faculty of Business and Economics', 'CCH_H1_3_05'),
('School of Chemical and Biomedical Engineering (D)', 'CCH_H1_5_197', 'School of Chemical and Biomedical Engineering', 'CCH_H1_4_18', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Faculty of Engineering and Information Technology - Admin', 'CCH_H1_5_35', 'Faculty of Engineering and Information Technology, Admin, Centres and Institute', 'CCH_H1_4_17', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Faculty of Engineering and Information Technology - Centres and Institutes', 'CCH_H1_5_36', 'Faculty of Engineering and Information Technology, Admin, Centres and Institute', 'CCH_H1_4_17', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Department of Biomedical Engineering', 'CCH_H1_5_37', 'School of Chemical and Biomedical Engineering', 'CCH_H1_4_18', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Department of Chemical Engineering', 'CCH_H1_5_38', 'School of Chemical and Biomedical Engineering', 'CCH_H1_4_18', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('School of Computing and Information Systems (D)', 'CCH_H1_5_39', 'School of Computing and Information Systems', 'CCH_H1_4_19', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('School of Electrical, Mechanical and Infrastructure Engineering - Admin', 'CCH_H1_5_40', 'School of Electrical, Mechanical and Infrastructure Engineering', 'CCH_H1_4_20', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Department of Electrical and Electronic Engineering', 'CCH_H1_5_41', 'School of Electrical, Mechanical and Infrastructure Engineering', 'CCH_H1_4_20', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Department of Infrastructure Engineering', 'CCH_H1_5_42', 'School of Electrical, Mechanical and Infrastructure Engineering', 'CCH_H1_4_20', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Department of Mechanical Engineering', 'CCH_H1_5_43', 'School of Electrical, Mechanical and Infrastructure Engineering', 'CCH_H1_4_20', 'Faculty of Engineering and Information Technology', 'CCH_H1_3_06'),
('Faculty of Fine Arts and Music - Admin', 'CCH_H1_5_44', 'Faculty of Fine Arts and Music, Admin, Centres and Institute', 'CCH_H1_4_21', 'Faculty of Fine Arts and Music', 'CCH_H1_3_07'),
('Melbourne Conservatorium of Music', 'CCH_H1_5_46', 'Faculty of Fine Arts and Music (S)', 'CCH_H1_4_22', 'Faculty of Fine Arts and Music', 'CCH_H1_3_07'),
('Victorian College of the Arts', 'CCH_H1_5_47', 'Faculty of Fine Arts and Music (S)', 'CCH_H1_4_22', 'Faculty of Fine Arts and Music', 'CCH_H1_3_07'),
('School of BioSciences - Centres and Institutes', 'CCH_H1_5_100', 'School of BioSciences', 'CCH_H1_4_32', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Chemistry (D)', 'CCH_H1_5_101', 'School of Chemistry', 'CCH_H1_4_33', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Geography, Earth and Atmospheric Sciences (D)', 'CCH_H1_5_103', 'School of Geography, Earth and Atmospheric Sciences', 'CCH_H1_4_34', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Geography, Earth and Atmospheric Sciences - Centres and Institutes', 'CCH_H1_5_104', 'School of Geography, Earth and Atmospheric Sciences', 'CCH_H1_4_34', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Mathematics and Statistics (D)', 'CCH_H1_5_105', 'School of Mathematics and Statistics', 'CCH_H1_4_35', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Mathematics and Statistics - Centres and Institutes', 'CCH_H1_5_106', 'School of Mathematics and Statistics', 'CCH_H1_4_35', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Physics (D)', 'CCH_H1_5_107', 'School of Physics', 'CCH_H1_4_36', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Physics - Centres and Institutes', 'CCH_H1_5_108', 'School of Physics', 'CCH_H1_4_36', 'Faculty of Science', 'CCH_H1_3_08'),
('Melbourne Veterinary School (D)', 'CCH_H1_5_109', 'Melbourne Veterinary School', 'CCH_H1_4_37', 'Faculty of Science', 'CCH_H1_3_08'),
('Melbourne Veterinary School - Centres and Institutes', 'CCH_H1_5_110', 'Melbourne Veterinary School', 'CCH_H1_4_37', 'Faculty of Science', 'CCH_H1_3_08'),
('Faculty of Science - Admin', 'CCH_H1_5_96', 'Faculty of Science, Admin, Centres and Institute', 'CCH_H1_4_30', 'Faculty of Science', 'CCH_H1_3_08'),
('Faculty of Science - Centres and Institutes', 'CCH_H1_5_97', 'Faculty of Science, Admin, Centres and Institute', 'CCH_H1_4_30', 'Faculty of Science', 'CCH_H1_3_08'),
('School of Agriculture, Food and Ecosystem Sciences (D)', 'CCH_H1_5_98', 'School of Agriculture, Food and Ecosystem Sciences', 'CCH_H1_4_31', 'Faculty of Science', 'CCH_H1_3_08'),
('School of BioSciences (D)', 'CCH_H1_5_99', 'School of BioSciences', 'CCH_H1_4_32', 'Faculty of Science', 'CCH_H1_3_08'),
('Faculty of Education - Admin', 'CCH_H1_5_111', 'Faculty of Education, Admin, Centres and Institute', 'CCH_H1_4_38', 'Faculty of Education', 'CCH_H1_3_09'),
('Faculty of Education - Centres and Institutes', 'CCH_H1_5_112', 'Faculty of Education, Admin, Centres and Institute', 'CCH_H1_4_38', 'Faculty of Education', 'CCH_H1_3_09'),
('Faculty of Education (D)', 'CCH_H1_5_113', 'Faculty of Education (S)', 'CCH_H1_4_39', 'Faculty of Education', 'CCH_H1_3_09'),
('Melbourne Law School - Admin', 'CCH_H1_5_114', 'Melbourne Law School (S)', 'CCH_H1_4_40', 'Melbourne Law School', 'CCH_H1_3_10'),
('Melbourne Law School - Centres and Institutes', 'CCH_H1_5_115', 'Melbourne Law School (S)', 'CCH_H1_4_40', 'Melbourne Law School', 'CCH_H1_3_10'),
('Melbourne Law School (D)', 'CCH_H1_5_116', 'Melbourne Law School (S)', 'CCH_H1_4_40', 'Melbourne Law School', 'CCH_H1_3_10'),
('Office of the VP Advancement', 'CCH_H1_5_118', 'Advancement, Communications & Marketing', 'CCH_H1_4_42', 'Advancement, Communications & Marketing ', 'CCH_H1_3_11'),
('Advancement', 'CCH_H1_5_119', 'Advancement, Communications & Marketing', 'CCH_H1_4_42', 'Advancement, Communications & Marketing ', 'CCH_H1_3_11'),
('Communications and Marketing', 'CCH_H1_5_120', 'Advancement, Communications & Marketing', 'CCH_H1_4_42', 'Advancement, Communications & Marketing ', 'CCH_H1_3_11'),
('Office of the DVC Global, Culture and Engagement', 'CCH_H1_5_155', 'Global, Culture and Engagement (S)', 'CCH_H1_4_49', 'Global, Culture and Engagement', 'CCH_H1_3_12'),
('Engagement (GCE)', 'CCH_H1_5_162', 'Global, Culture and Engagement (S)', 'CCH_H1_4_49', 'Global, Culture and Engagement', 'CCH_H1_3_12'),
('Melbourne Theatre Company', 'CCH_H1_5_164', 'Global, Culture and Engagement (S)', 'CCH_H1_4_49', 'Global, Culture and Engagement', 'CCH_H1_3_12'),
('Global (GCE)', 'CCH_H1_5_202', 'Global, Culture and Engagement (S)', 'CCH_H1_4_49', 'Global, Culture and Engagement', 'CCH_H1_3_12'),
('Culture (GCE)', 'CCH_H1_5_203', 'Global, Culture and Engagement (S)', 'CCH_H1_4_49', 'Global, Culture and Engagement', 'CCH_H1_3_12'),
('Deputy Vice-Chancellor (Academic)', 'CCH_H1_5_170', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Deputy Vice-Chancellor (Indigenous)', 'CCH_H1_5_171', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Melbourne University Sport', 'CCH_H1_5_172', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('People and Community', 'CCH_H1_5_173', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Office of the Provost (D)', 'CCH_H1_5_188', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Melbourne Online', 'CCH_H1_5_198', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Melbourne Professional Education (MPE)', 'CCH_H1_5_34', 'Office of the Provost (S)', 'CCH_H1_4_50', 'Office of the Provost', 'CCH_H1_3_13'),
('Office of the Vice-Chancellor (D)', 'CCH_H1_5_174', 'Office of the Vice-Chancellor (S)', 'CCH_H1_4_51', 'Office of the Vice-Chancellor', 'CCH_H1_3_14'),
('Office of the DVC Research', 'CCH_H1_5_175', 'Research & Enterprise (S)', 'CCH_H1_4_52', 'Research & Enterprise', 'CCH_H1_3_15'),
('Atlantic Fellows for Social Equity', 'CCH_H1_5_176', 'Research & Enterprise (S)', 'CCH_H1_4_52', 'Research & Enterprise', 'CCH_H1_3_15'),
('Melbourne Connect', 'CCH_H1_5_178', 'Research & Enterprise (S)', 'CCH_H1_4_52', 'Research & Enterprise', 'CCH_H1_3_15'),
('Corporate', 'CCH_H1_5_184', 'University Corporate', 'CCH_H1_4_53', 'University Central Reporting Group', 'CCH_H1_3_16'),
('Service Recipients', 'CCH_H1_5_185', 'University Corporate', 'CCH_H1_4_53', 'University Central Reporting Group', 'CCH_H1_3_16'),
('Nossal Institute Ltd (D)', 'CCH_H1_5_187', 'Nossal Institute Ltd (S)', 'CCH_H1_4_55', 'Nossal Institute Ltd', 'CCH_H1_3_17'),
('UM Commercialisation Pty Ltd (D)', 'CCH_H1_5_189', 'UM Commercialisation Pty Ltd (S)', 'CCH_H1_4_56', 'UM Commercialisation Pty Ltd', 'CCH_H1_3_18'),
('UM Commercialisation Trust (D)', 'CCH_H1_5_190', 'UM Commercialisation Trust (S)', 'CCH_H1_4_57', 'UM Commercialisation Trust', 'CCH_H1_3_19'),
('UMELB (Singapore) (D)', 'CCH_H1_5_191', 'UMELB (Singapore) (S)', 'CCH_H1_4_58', 'UMELB (Singapore)', 'CCH_H1_3_20'),
('UOM Commercial Ltd (D)', 'CCH_H1_5_192', 'UOM Commercial Ltd (S)', 'CCH_H1_4_59', 'UOM Commercial Ltd', 'CCH_H1_3_21'),
('Melbourne Business School Limited Group (D)', 'CCH_H1_5_193', 'Melbourne Business School Limited Group (S)', 'CCH_H1_4_60', 'Melbourne Business School Limited Group', 'CCH_H1_3_22'),
('UoM International Holdings Limited Group (D)', 'CCH_H1_5_194', 'UoM International Holdings Limited Group (S)', 'CCH_H1_4_61', 'UoM International Holdings Limited Group', 'CCH_H1_3_23'),
('Ao Mo Da (Beijing) Consulting Co. Ltd (D)', 'CCH_H1_5_195', 'Ao Mo Da (Beijing) Consulting Co. Ltd (S)', 'CCH_H1_4_62', 'Ao Mo Da (Beijing) Consulting Co. Ltd', 'CCH_H1_3_24'),
('Unimelb Germany GmbH (D)', 'CCH_H1_5_196', 'Unimelb Germany GmbH (S)', 'CCH_H1_4_63', 'Unimelb Germany GmbH ', 'CCH_H1_3_25');

-- Index on department
CREATE INDEX idx_lookup_department ON department_and_faculty(department);